// ****Action***8

// cake shop
const GET_CAKE = "GET_CAKE";
// icecream shop
const BUY_ICECREAMS = "GET_ICECREAMS";
//uer async action
const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
module.exports = {
  GET_CAKE,
  BUY_ICECREAMS,
  FETCH_USER_REQUEST,
  FETCH_USER_SUCCESS,
  FETCH_USER_FAILURE,
};
